module.exports = [
    'ABONO',
    'ABONO EM DINHEIRO',
    'ABONO PECUNIÁRIO',
    'ABONO PECUNIARIO',
    'ABONO FÉRIAS',
    'ABONO FERIAS',
    'ABONO FÉRIAZ',
    'ABONO FERIAZ',
    'ABONO DE FÉRIAS',
    'ABONO DE FERIAS',
    'ABONO DE FÉRIAZ',
    'ABONO DE FERIAZ',
]