module.exports = [
    'O QUE E {{entity}}', 
    'O QUE É {{entity}}',
    'COMO FUNCIONA {{entity}}',
    '* CONSEGUE ME EXPLICAR O QUE E {{entity}}',
    '* CONSEGUE ME EXPLICAR O QUE É {{entity}}',
    'EU QUERO MAIS INFORMAÇÕES SOBRE {{entity}}',
    'EU QUERO MAIS INFORMACOES SOBRE {{entity}}',
    'QUERO SABER MAIS SOBRE {{entity}}',
    'QUAIS AS FUNÇÕES DE {{entity}}',
    'QUAIS AS FUNCOES DE {{entity}}',
    'QUAL O SIGNIFICADO * {{entity}}',
    'VOCÊ PODE ME EXPLICAR {{entity}}',
    'VOCE PODE ME EXPLICAR {{entity}}',
    'EU QUERO SABER SOBRE {{entity}}',
    'QUAL É A FUNÇÃO * {{entity}}',
    'QUAL É A FUNCAO * {{entity}}',
    'O QUE SIGNIFICA {{entity}}',
    'PARA QUE SERVER {{entity}}',
    // 'QUAL É A FUNÇÃO DO {{entity}}',
    '* PODE ME EXPLICAR SOBRE {{entity}}',
    'PARA QUE SERVEM AS {{entity}}',
    // 'QUAL É A FUNÇÃO DAS {{entity}}',
]
